package com.google.android.apps.signalong.jsonentities;

/**
 * The AuthResponse class is the authenticate response body. This is autogenerated by running GSON
 * format plugin from Android Studio.
 */
public class AuthResponse extends BaseResponse {


  private DataBean data;

  public DataBean getData() {
    return data;
  }

  public void setData(DataBean data) {
    this.data = data;
  }

  /** The DataBean class is real data, that contains access token and refresh token. */
  public static class DataBean {

    private String refresh;
    private String access;

    public String getRefresh() {
      return refresh;
    }

    public void setRefresh(String refresh) {
      this.refresh = refresh;
    }

    public String getAccess() {
      return access;
    }

    public void setAccess(String access) {
      this.access = access;
    }
  }
}
