package com.google.android.apps.signalong.jsonentities;

import com.google.gson.annotations.SerializedName;

/**
 * The ProfileResponse class is the profile response body. This is autogenerated by running GSON
 * format plugin from Android Studio.
 */
public class ProfileResponse extends BaseResponse{

  private DataBean data;

  public DataBean getData() {
    return data;
  }

  public void setData(DataBean data) {
    this.data = data;
  }

  /** The DataBean class is real data, that contains username and score. */
  public static class DataBean {

    private int id;
    private String username;
    private ScoresBean scores;

    public int getId() {
      return id;
    }

    public void setId(int id) {
      this.id = id;
    }

    public String getUsername() {
      return username;
    }

    public void setUsername(String username) {
      this.username = username;
    }

    public ScoresBean getScores() {
      return scores;
    }

    public void setScores(ScoresBean scores) {
      this.scores = scores;
    }
    /**
     * The ScoresBean class is real data, that contains review video score and create video score
     * etc.
     */
    public static class ScoresBean {

      @SerializedName("video_review_score")
      private int videoReviewScore;
      /* Video is a video file that is uploaded by the user based on the value of the gloss.*/
      @SerializedName("create_video_score")
      private int videoCreationScore;
      /* Gloss is a text, the label of the same videos created by different people.*/
      @SerializedName("create_gloss_score")
      private int glossCreationScore;

      @SerializedName("video_quality_score")
      private int videoQualityScore;

      public int getVideoReviewScore() {
        return videoReviewScore;
      }

      public void setVideoReviewScore(int videoReviewScore) {
        this.videoReviewScore = videoReviewScore;
      }

      public int getVideoCreationScore() {
        return videoCreationScore;
      }

      public void setVideoCreationScore(int videoCreationScore) {
        this.videoCreationScore = videoCreationScore;
      }

      public int getGlossCreationScore() {
        return glossCreationScore;
      }

      public void setGlossCreationScore(int glossCreationScore) {
        this.glossCreationScore = glossCreationScore;
      }

      public int getVideoQualityScore() {
        return videoQualityScore;
      }

      public void setVideoQualityScore(int videoQualityScore) {
        this.videoQualityScore = videoQualityScore;
      }
    }
  }
}
