package com.google.android.apps.signalong.jsonentities;

/**
 * The RefreshRequest class is the refresh request body. This is autogenerated by running GSON
 * format plugin from Android Studio.
 */
public class RefreshRequest {

  private String refresh;

  public RefreshRequest(String refresh) {
    this.refresh = refresh;
  }

  public String getRefresh() {
    return refresh;
  }

  public void setRefresh(String refresh) {
    this.refresh = refresh;
  }
}
