package com.google.android.apps.signalong.jsonentities;

/**
 * The ReviewVideoResponse class is the review video status response body. This is autogenerated by
 * running GSON format plugin from Android Studio.
 */
public class ReviewVideoResponse {

  private int code;
  private DataBean data;

  public int getCode() {
    return code;
  }

  public void setCode(int code) {
    this.code = code;
  }

  public DataBean getData() {
    return data;
  }

  public void setData(DataBean data) {
    this.data = data;
  }
  /** The DataBean class is real data, that contains uuid and value. */
  public static class DataBean {

    private String uuid;
    private int value;

    public String getUuid() {
      return uuid;
    }

    public void setUuid(String uuid) {
      this.uuid = uuid;
    }

    public int getValue() {
      return value;
    }

    public void setValue(int value) {
      this.value = value;
    }
  }
}
