package com.google.android.apps.signalong.jsonentities;

import com.google.gson.annotations.SerializedName;
import java.util.List;

/**
 * The SignPromptBatchResponse class is the create bunch response body. This is autogenerated by
 * running GSON format plugin from Android Studio.
 */
public class SignPromptBatchResponse {

  private int code;
  private List<DataBean> data;

  public int getCode() {
    return code;
  }

  public void setCode(int code) {
    this.code = code;
  }

  public List<DataBean> getData() {
    return data;
  }

  public void setData(List<DataBean> data) {
    this.data = data;
  }
  /** The DataBean class is real data, that contains id and sample text. */
  public static class DataBean {

    private int id;
    private String text;

    @SerializedName("sign_type")
    private int signType;

    @SerializedName("video_count")
    private Object videoCount;

    @SerializedName("sample_video")
    private SampleVideoBean sampleVideo;

    public SampleVideoBean getSampleVideo() {
      return sampleVideo;
    }

    public void setSampleVideo(SampleVideoBean sampleVideo) {
      this.sampleVideo = sampleVideo;
    }

    public int getId() {
      return id;
    }

    public void setId(int id) {
      this.id = id;
    }

    public String getText() {
      return text;
    }

    public void setText(String text) {
      this.text = text;
    }

    public int getSignType() {
      return signType;
    }

    public void setSignType(int signType) {
      this.signType = signType;
    }

    public Object getVideoCount() {
      return videoCount;
    }

    public void setVideoCount(Object videoCount) {
      this.videoCount = videoCount;
    }
    /** The SampleVideoBean class is real data, that contains video path. */
    public static class SampleVideoBean {

      @SerializedName("video_path")
      private String videoPath;

      public String getVideoPath() {
        return videoPath;
      }

      public void setVideoPath(String videoPath) {
        this.videoPath = videoPath;
      }
    }
  }
}
