package com.google.android.apps.signalong.jsonentities;

import android.os.Parcel;
import android.os.Parcelable;
import com.google.android.apps.signalong.jsonentities.VideoListResponse.DataBeanList;
import com.google.android.apps.signalong.jsonentities.VideoListResponse.DataBeanList.DataBean;
import com.google.gson.annotations.SerializedName;
import java.util.ArrayList;
import java.util.List;

/**
 * The SignPromptBatchResponse class is the create bunch response body. This is autogenerated by
 * running GSON format plugin from Android Studio.
 */
public class SignPromptBatchResponse extends BaseResponse {

  private List<DataBean> data;

  public List<DataBean> getData() {
    return data;
  }

  public void setData(List<DataBean> data) {
    this.data = data;
  }

  public SignPromptBatchResponse(DataBean data) {
    this.data = new ArrayList<DataBean>();
    this.data.add(data);
  }
  /**
   * The DataBean class is real data, that contains id and sample text.
   */
  public static class DataBean implements Parcelable {

    private int id;
    private String text;

    @SerializedName("gloss_type")
    private int glossType;

    @SerializedName("video_count")
    private int videoCount;

    @SerializedName("sample_video")
    private SampleVideoBean sampleVideo;

    private int duration;

    public static final Creator<DataBean> CREATOR =
        new Creator<DataBean>() {
          @Override
          public DataBean createFromParcel(Parcel source) {
            return new DataBean(source);
          }

          @Override
          public DataBean[] newArray(int size) {
            return new DataBean[size];
          }
        };

    protected DataBean(Parcel in) {
      this.id = in.readInt();
      this.text = in.readString();
      this.glossType = in.readInt();
      this.videoCount = in.readInt();
      this.duration = in.readInt();
      this.sampleVideo = in.readParcelable(SampleVideoBean.class.getClassLoader());
    }

    @Override
    public int describeContents() {
      return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
      dest.writeInt(this.id);
      dest.writeString(this.text);
      dest.writeInt(this.glossType);
      dest.writeInt(this.videoCount);
      dest.writeInt(this.duration);
      dest.writeParcelable(this.sampleVideo, flags);
    }

    public int getId() {
      return id;
    }

    public void setId(int id) {
      this.id = id;
    }

    public String getText() {
      return text;
    }

    public int getDuration() {
      return duration;
    }

    public void setText(String text) {
      this.text = text;
    }

    public SampleVideoBean getSampleVideo() {
      return sampleVideo;
    }

    public void setSampleVideo(SampleVideoBean sampleVideo) {
      this.sampleVideo = sampleVideo;
    }

    /**
     * The SampleVideoBean class is real data, that contains video path.
     */
    public static class SampleVideoBean implements Parcelable {

      @SerializedName("video_path")
      private String videoPath;

      private String thumbnail;

      public SampleVideoBean() {}

      @Override
      public int describeContents() { return 0; }

      @Override
      public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(videoPath);
        dest.writeString(thumbnail);
      }

      protected SampleVideoBean(Parcel in) {
        this.videoPath = in.readString();
        this.thumbnail = in.readString();
      }

      static public final Parcelable.Creator CREATOR = new Parcelable.Creator() {
        public SampleVideoBean createFromParcel(Parcel in) {
          return new SampleVideoBean(in);
        }

        public SampleVideoBean[] newArray(int size) {
          return new SampleVideoBean[size];
        }
      };

      public String getVideoPath() {
        return videoPath;
      }
      public String getThumbnailPath() { return thumbnail; }
    }
  }
}
