package com.google.android.apps.signalong.jsonentities;

import android.os.Parcel;
import android.os.Parcelable.Creator;
import com.google.gson.annotations.SerializedName;
import java.util.List;

/**
 * The VideoListResponse class is the video data list result response body. This is autogenerated by
 * running GSON format plugin from Android Studio.
 */
public class VideoListResponse extends BaseResponse{

  @SerializedName("data")
  private DataBeanList dataBeanList;

  public DataBeanList getDataBeanList() {
    return dataBeanList;
  }

  public void setDataBeanList(DataBeanList dataBeanList) {
    this.dataBeanList = dataBeanList;
  }

  /** DataBeanList wraps multiple item data. */
  public static class DataBeanList {

    /* total is the total amount of video, not the size of the data that has already been loaded.*/
    private int total;
    private int next;
    private List<DataBean> data;

    public int getTotal() {
      return total;
    }

    public int getNext() {
      return next;
    }

    public void setNext(int next) {
      this.next = next;
    }

    public List<DataBean> getData() {
      return data;
    }

    public void setData(List<DataBean> data) {
      this.data = data;
    }

    /** The DataBean class is real data, that contains gloss id and gloss text. */
    public static class DataBean implements android.os.Parcelable {

      public static final Creator<DataBean> CREATOR =
          new Creator<DataBean>() {
            @Override
            public DataBean createFromParcel(Parcel source) {
              return new DataBean(source);
            }

            @Override
            public DataBean[] newArray(int size) {
              return new DataBean[size];
            }
          };

      @SerializedName("gloss_id")
      private int glossId;

      @SerializedName("gloss_text")
      private String glossText;

      @SerializedName("created_time")
      private int createdTime;

      @SerializedName("video_path")
      private String videoPath;

      private String uuid;
      private String thumbnail;

      public DataBean() {}

      protected DataBean(Parcel in) {
        this.glossId = in.readInt();
        this.glossText = in.readString();
        this.createdTime = in.readInt();
        this.videoPath = in.readString();
        this.uuid = in.readString();
        this.thumbnail = in.readString();
      }

      @Override
      public int describeContents() {
        return 0;
      }

      @Override
      public void writeToParcel(Parcel dest, int flags) {
        dest.writeInt(this.glossId);
        dest.writeString(this.glossText);
        dest.writeInt(this.createdTime);
        dest.writeString(this.videoPath);
        dest.writeString(this.uuid);
        dest.writeString(this.thumbnail);
      }

      public int getGlossId() {
        return glossId;
      }

      public void setGlossId(int glossId) {
        this.glossId = glossId;
      }

      public String getGlossText() {
        return glossText;
      }

      public void setGlossText(String glossText) {
        this.glossText = glossText;
      }

      public int getCreatedTime() {
        return createdTime;
      }

      public void setCreatedTime(int createdTime) {
        this.createdTime = createdTime;
      }

      public String getVideoPath() {
        return videoPath;
      }

      public void setVideoPath(String videoPath) {
        this.videoPath = videoPath;
      }

      public String getUuid() {
        return uuid;
      }

      public void setUuid(String uuid) {
        this.uuid = uuid;
      }

      public String getThumbnail() {
        return thumbnail;
      }

      public void setThumbnail(String thumbnail) {
        this.thumbnail = thumbnail;
      }
    }
  }
}
